### ISSUE TITLE
Incorrect aspect ratio

### ISSUE THREAD

**Issue by anonieee** [karatsuba/workflowy-link-preview#26]
All images I tried embedding has an incorrect aspect ratio. Any fix for this?

**Comment by anonieee** [comment]
Okay, from what I can tell the aspect ratio becomes incorrect if the image is wider than the canvas. So in attempt to fit it, the image gets resized horizontally, squishing it. Try to Ctrl+Scroll and zoom in Workflowy and the image will start to get distorted horizontally.

**Comment by karatsuba** [comment]
Ok, I see what you mean. Going to improve it in the next release 🤞

**Comment by karatsuba** [comment]
Fixed by (https://github.com/karatsuba/workflowy-link-preview/pull/29).

**Comment by anonieee** [comment]
Thank you, how do I package this into an extension? Or will you push an updated to the store soon?

**Comment by karatsuba** [comment]
@anonieee, I've just submitted a new version to Chrome Web Store. After successful review you should get the updated version automatically 😄
